In [1]:
!python3.12 -m pip install openpyxl pandas

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/radovanhodor/Library/Python/3.12/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/radovanhodor/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
from pathlib import Path

# Path to the folder containing PEMMDB xlsx files
PEMMDB_DIR = Path("../data/tyndp2024/PEMMDB2/2030")
DSR_SHEET = "DSR"
ROWS_TO_READ = 9
SKIP_HEADER_ROWS = 6   # skip first 6 rows (non-data header rows)
SKIP_TAIL_ROWS = 2     # skip last 2 rows

all_dfs = []

for xlsx_file in sorted(PEMMDB_DIR.glob("*.xlsx")):
    # Extract country/node code from filename, e.g. PEMMDB_SK00_NationalTrends_2030.xlsx -> SK00
    node = xlsx_file.stem.split("_")[1]
    
    try:
        df = pd.read_excel(xlsx_file, sheet_name=DSR_SHEET, nrows=ROWS_TO_READ, header=SKIP_HEADER_ROWS)
        # Drop last 2 rows
        df = df.iloc[:-SKIP_TAIL_ROWS]
        df.insert(0, "node", node)          # add source file identifier
        df.insert(1, "source_file", xlsx_file.name)
        all_dfs.append(df)
        print(f"✓ {xlsx_file.name}")
    except Exception as e:
        print(f"✗ {xlsx_file.name}: {e}")

# Combine all results into a single DataFrame
dsr_df = pd.concat(all_dfs, ignore_index=True) if all_dfs else pd.DataFrame()
print(f"\nTotal rows collected: {len(dsr_df)}")

✓ PEMMDB_AL00_NationalTrends_2030.xlsx
✓ PEMMDB_AT00_NationalTrends_2030.xlsx
✓ PEMMDB_BA00_NationalTrends_2030.xlsx
✓ PEMMDB_BE00_NationalTrends_2030.xlsx
✓ PEMMDB_BEOF_NationalTrends_2030.xlsx
✓ PEMMDB_BG00_NationalTrends_2030.xlsx
✓ PEMMDB_CH00_NationalTrends_2030.xlsx
✓ PEMMDB_CY00_NationalTrends_2030.xlsx
✓ PEMMDB_CZ00_NationalTrends_2030.xlsx
✓ PEMMDB_DE00_NationalTrends_2030.xlsx
✓ PEMMDB_DEKF_NationalTrends_2030.xlsx
✓ PEMMDB_DKBH_NationalTrends_2030.xlsx
✓ PEMMDB_DKE1_NationalTrends_2030.xlsx
✓ PEMMDB_DKKF_NationalTrends_2030.xlsx
✓ PEMMDB_DKNS_NationalTrends_2030.xlsx
✓ PEMMDB_DKW1_NationalTrends_2030.xlsx
✓ PEMMDB_DZ00_NationalTrends_2030.xlsx
✓ PEMMDB_EE00_NationalTrends_2030.xlsx
✓ PEMMDB_EEOF_NationalTrends_2030.xlsx
✓ PEMMDB_EG00_NationalTrends_2030.xlsx
✓ PEMMDB_ES00_NationalTrends_2030.xlsx
✓ PEMMDB_FI00_NationalTrends_2030.xlsx
✓ PEMMDB_FR00_NationalTrends_2030.xlsx
✓ PEMMDB_FR15_NationalTrends_2030.xlsx
✓ PEMMDB_GE00_NationalTrends_2030.xlsx
✓ PEMMDB_GR00_NationalTrends_2030.xlsx
✓ PEMMDB_GR03_NationalTrends_2030.xlsx
✓ PEMMDB_HR00_NationalTrends_2030.xlsx
✓ PEMMDB_HU00_NationalTrends_2030.xlsx
✓ PEMMDB_IE00_NationalTrends_2030.xlsx
✓ PEMMDB_IL00_NationalTrends_2030.xlsx
✓ PEMMDB_ITA00_NationalTrends_2030.xlsx
✓ PEMMDB_ITCA_NationalTrends_2030.xlsx
✓ PEMMDB_ITCN_NationalTrends_2030.xlsx
✓ PEMMDB_ITCS_NationalTrends_2030.xlsx
✓ PEMMDB_ITN1_NationalTrends_2030.xlsx
✓ PEMMDB_ITS1_NationalTrends_2030.xlsx
✓ PEMMDB_ITSA_NationalTrends_2030.xlsx
✓ PEMMDB_ITSI_NationalTrends_2030.xlsx
✓ PEMMDB_LT00_NationalTrends_2030.xlsx
✓ PEMMDB_LTOF_NationalTrends_2030.xlsx
✓ PEMMDB_LUB1_NationalTrends_2030.xlsx
✓ PEMMDB_LUF1_NationalTrends_2030.xlsx
✓ PEMMDB_LUG1_NationalTrends_2030.xlsx
✓ PEMMDB_LUV1_NationalTrends_2030.xlsx
✓ PEMMDB_LV00_NationalTrends_2030.xlsx
✓ PEMMDB_LY00_NationalTrends_2030.xlsx
✓ PEMMDB_MA00_NationalTrends_2030.xlsx
✓ PEMMDB_MD00_NationalTrends_2030.xlsx
✓ PEMMDB_ME00_NationalTrends_2030.xlsx
✓ PEMMDB_MK00_NationalTrends_2030.xlsx
✓ PEMMDB_MT00_NationalTrends_2030.xlsx
✓ PEMMDB_NL00_NationalTrends_2030.xlsx
✓ PEMMDB_NL60_NationalTrends_2030.xlsx
✓ PEMMDB_NL6H_NationalTrends_2030.xlsx
✓ PEMMDB_NLA0_NationalTrends_2030.xlsx
✓ PEMMDB_NLBH_NationalTrends_2030.xlsx
✓ PEMMDB_NLLL_NationalTrends_2030.xlsx
✓ PEMMDB_NOM1_NationalTrends_2030.xlsx
✓ PEMMDB_NON1_NationalTrends_2030.xlsx
✓ PEMMDB_NOS0_NationalTrends_2030.xlsx
✓ PEMMDB_PL00_NationalTrends_2030.xlsx
✓ PEMMDB_PS00_NationalTrends_2030.xlsx
✓ PEMMDB_PT00_NationalTrends_2030.xlsx
✓ PEMMDB_RO00_NationalTrends_2030.xlsx
✓ PEMMDB_RS00_NationalTrends_2030.xlsx
✓ PEMMDB_SE01_NationalTrends_2030.xlsx
✓ PEMMDB_SE02_NationalTrends_2030.xlsx
✓ PEMMDB_SE03_NationalTrends_2030.xlsx
✓ PEMMDB_SE04_NationalTrends_2030.xlsx
✓ PEMMDB_SI00_NationalTrends_2030.xlsx
✓ PEMMDB_SK00_NationalTrends_2030.xlsx
✓ PEMMDB_TN00_NationalTrends_2030.xlsx
✓ PEMMDB_TR00_NationalTrends_2030.xlsx
✓ PEMMDB_UA00_NationalTrends_2030.xlsx
✓ PEMMDB_UK00_NationalTrends_2030.xlsx
✓ PEMMDB_UKNI_NationalTrends_2030.xlsx
✗ ~$PEMMDB_DE00_NationalTrends_2030.xlsx: Excel file format cannot be determined, you must specify an engine manually.
✗ ~$PEMMDB_ITSA_NationalTrends_2030.xlsx: Excel file format cannot be determined, you must specify an engine manually.

Total rows collected: 539

In [3]:
dsr_df.shape

(539, 24)

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
display(dsr_df.head(100))

,node,source_file,Scenario,NationalTrends,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 1,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,AL00,PEMMDB_AL00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AL00,PEMMDB_AL00_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AL00,PEMMDB_AL00_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AL00,PEMMDB_AL00_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AL00,PEMMDB_AL00_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,AL00,PEMMDB_AL00_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AL00,PEMMDB_AL00_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,AT00,PEMMDB_AT00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,AT00,PEMMDB_AT00_NationalTrends_2030.xlsx,NaN,Capacity,700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,AT00,PEMMDB_AT00_NationalTrends_2030.xlsx,NaN,Units,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,AT00,PEMMDB_AT00_NationalTrends_2030.xlsx,NaN,Hours,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,AT00,PEMMDB_AT00_NationalTrends_2030.xlsx,NaN,Price,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,AT00,PEMMDB_AT00_NationalTrends_2030.xlsx,NaN,Climate year start,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,AT00,PEMMDB_AT00_NationalTrends_2030.xlsx,NaN,Climate year end,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,BA00,PEMMDB_BA00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,BA00,PEMMDB_BA00_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,BA00,PEMMDB_BA00_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,BA00,PEMMDB_BA00_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,BA00,PEMMDB_BA00_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,BA00,PEMMDB_BA00_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,BA00,PEMMDB_BA00_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,BE00,PEMMDB_BE00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 2,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,BE00,PEMMDB_BE00_NationalTrends_2030.xlsx,NaN,Capacity,131,53.8,454,634,540.824028,193,202.651658,620.384935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,BE00,PEMMDB_BE00_NationalTrends_2030.xlsx,NaN,Units,3,3,3,3,6,3,3,3,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,BE00,PEMMDB_BE00_NationalTrends_2030.xlsx,NaN,Hours,1,24,2,4,8,24,24,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,BE00,PEMMDB_BE00_NationalTrends_2030.xlsx,NaN,Price,1000,1000,2000,1500,500,300,178,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,BE00,PEMMDB_BE00_NationalTrends_2030.xlsx,NaN,Climate year start,1982,1982,1982,1982,1982,1982,1982,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,BE00,PEMMDB_BE00_NationalTrends_2030.xlsx,NaN,Climate year end,2016,2016,2016,2016,2016,2016,2016,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,BEOF,PEMMDB_BEOF_NationalTrends_2030.xlsx,NaN,NaN,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,Demand Side Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,BEOF,PEMMDB_BEOF_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,BEOF,PEMMDB_BEOF_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,BEOF,PEMMDB_BEOF_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,BEOF,PEMMDB_BEOF_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,BEOF,PEMMDB_BEOF_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,BEOF,PEMMDB_BEOF_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,BG00,PEMMDB_BG00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,BG00,PEMMDB_BG00_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,BG00,PEMMDB_BG00_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,BG00,PEMMDB_BG00_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,BG00,PEMMDB_BG00_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,BG00,PEMMDB_BG00_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,BG00,PEMMDB_BG00_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,CH00,PEMMDB_CH00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,CH00,PEMMDB_CH00_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,CH00,PEMMDB_CH00_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,CH00,PEMMDB_CH00_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,CH00,PEMMDB_CH00_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,CH00,PEMMDB_CH00_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,CH00,PEMMDB_CH00_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,CY00,PEMMDB_CY00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,CY00,PEMMDB_CY00_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,CY00,PEMMDB_CY00_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,CY00,PEMMDB_CY00_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,CY00,PEMMDB_CY00_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,CY00,PEMMDB_CY00_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,CY00,PEMMDB_CY00_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,CZ00,PEMMDB_CZ00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,CZ00,PEMMDB_CZ00_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,CZ00,PEMMDB_CZ00_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,CZ00,PEMMDB_CZ00_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,CZ00,PEMMDB_CZ00_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,CZ00,PEMMDB_CZ00_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,CZ00,PEMMDB_CZ00_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 2,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Price Band 11,NaN,Price Band 12,Price Band 13,Price Band 14,Price Band 14,Price Band 14,Price Band 15,Price Band 15,Price Band 15
64,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Capacity,288.5,1838.7,2.7,3.2,152.4,200.1,49.4,103.6,1307.2,304.2,259.1,NaN,19,471.7,10000,10000,10000,8800,8800,8800
65,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Units,7,14,7,7,7,7,7,7,7,21,7,NaN,7,21,1,1,1,1,1,1
66,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Hours,8,24,6,2,15,24,1,6,24,24,24,NaN,24,24,24,24,24,24,24,24
67,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Price,5,5,256,820,461,390,564,487,10,20,115,NaN,150,200,87.1,87.1,87.1,43.6,43.6,43.6
68,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Climate year start,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,NaN,1982,1982,1995,2008,2009,1995,2008,2009
69,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Climate year end,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,NaN,2016,2016,1995,2008,2009,1995,2008,2009
70,DEKF,PEMMDB_DEKF_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,DEKF,PEMMDB_DEKF_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,DEKF,PEMMDB_DEKF_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,DEKF,PEMMDB_DEKF_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,DEKF,PEMMDB_DEKF_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,DEKF,PEMMDB_DEKF_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,DEKF,PEMMDB_DEKF_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,DKBH,PEMMDB_DKBH_NationalTrends_2030.xlsx,NaN,NaN,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,Demand Side Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,DKBH,PEMMDB_DKBH_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,DKBH,PEMMDB_DKBH_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,DKBH,PEMMDB_DKBH_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,DKBH,PEMMDB_DKBH_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,DKBH,PEMMDB_DKBH_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,DKBH,PEMMDB_DKBH_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,DKE1,PEMMDB_DKE1_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,DKE1,PEMMDB_DKE1_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,DKE1,PEMMDB_DKE1_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,DKE1,PEMMDB_DKE1_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,DKE1,PEMMDB_DKE1_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,DKE1,PEMMDB_DKE1_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,DKE1,PEMMDB_DKE1_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,DKKF,PEMMDB_DKKF_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,DKKF,PEMMDB_DKKF_NationalTrends_2030.xlsx,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,DKKF,PEMMDB_DKKF_NationalTrends_2030.xlsx,NaN,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Activation price of -1 marks bands not to be m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,DKKF,PEMMDB_DKKF_NationalTrends_2030.xlsx,NaN,Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,DKKF,PEMMDB_DKKF_NationalTrends_2030.xlsx,NaN,Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,DKKF,PEMMDB_DKKF_NationalTrends_2030.xlsx,NaN,Climate year start,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,DKKF,PEMMDB_DKKF_NationalTrends_2030.xlsx,NaN,Climate year end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,DKNS,PEMMDB_DKNS_NationalTrends_2030.xlsx,NaN,NaN,Price Band 1,Price Band 1,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Includes only Market Response (user not willin...,Demand Side Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,DKNS,PEMMDB_DKNS_NationalTrends_2030.xlsx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Capacity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Filter rows for Germany (DE00)
dsr_df[dsr_df["node"] == "DE00"]

,node,source_file,Scenario,NationalTrends,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 1,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
63,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Demand Side Response,Price Band 1,Price Band 2,Price Band 3,Price Band 4,Price Band 5,Price Band 6,Price Band 7,Price Band 8,Price Band 9,Price Band 10,Price Band 11,NaN,Price Band 12,Price Band 13,Price Band 14,Price Band 14,Price Band 14,Price Band 15,Price Band 15,Price Band 15
64,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Capacity,288.5,1838.7,2.7,3.2,152.4,200.1,49.4,103.6,1307.2,304.2,259.1,NaN,19,471.7,10000,10000,10000,8800,8800,8800
65,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Units,7,14,7,7,7,7,7,7,7,21,7,NaN,7,21,1,1,1,1,1,1
66,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Hours,8,24,6,2,15,24,1,6,24,24,24,NaN,24,24,24,24,24,24,24,24
67,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Price,5,5,256,820,461,390,564,487,10,20,115,NaN,150,200,87.1,87.1,87.1,43.6,43.6,43.6
68,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Climate year start,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,NaN,1982,1982,1995,2008,2009,1995,2008,2009
69,DE00,PEMMDB_DE00_NationalTrends_2030.xlsx,NaN,Climate year end,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,NaN,2016,2016,1995,2008,2009,1995,2008,2009

In [6]:
import numpy as np

values = [288.5, 1838.7, 2.7, 3.2, 152.4, 200.1, 49.4, 103.6, 1307.2, 304.2, 259.1, np.nan, 19, 471.7, 10000, 10000, 10000, 8800, 8800, 8800]

total = np.nansum(values) - 20000 - 8800 - 8800
print(f"Sum (excluding NaN): {total:,.1f}")

Sum (excluding NaN): 23,799.8

In [7]:
# Transpose DSR data: Price Bands become rows, attributes become columns
#
# In dsr_df each row is one attribute (Capacity, Units, Hours, Price, ...),
# the 4th column (index 3 after node/source_file) holds the attribute name,
# and the remaining columns hold values per Price Band.
#
# We want one row per (node, price_band) with columns: Capacity, Units, Hours, Price, ...

ATTRIBUTE_COL = 3   # positional index of the column holding the attribute name (after node, source_file, unnamed)

all_transposed = []

for node, group in dsr_df.groupby("node"):
    group = group.reset_index(drop=True)

    # The attribute name column is the 4th column (index 3)
    attr_col = group.columns[ATTRIBUTE_COL]

    # Row 0 of this group contains Price Band names
    price_bands_raw = group.iloc[0, ATTRIBUTE_COL + 1:].tolist()

    # Deduplicate price band names (e.g. "Price Band 14" appears 3x for different climate years)
    seen = {}
    unique_bands = []
    for name in price_bands_raw:
        if pd.isna(name):
            unique_bands.append(name)
            continue
        if name in seen:
            seen[name] += 1
            unique_bands.append(f"{name}_{seen[name]}")
        else:
            seen[name] = 1
            unique_bands.append(name)

    # Remaining rows are the actual attribute rows (Capacity, Units, Hours, Price, ...)
    attr_df = group.iloc[1:].copy()
    attr_df = attr_df.set_index(attr_col)
    attr_df.index = attr_df.index.astype(str)
    attr_df.index.name = None
    attr_df = attr_df.iloc[:, ATTRIBUTE_COL:]   # drop node, source_file, unnamed col
    attr_df.columns = range(len(attr_df.columns))
    attr_df.columns = unique_bands

    # Drop NaN separator columns
    attr_df = attr_df[[c for c in attr_df.columns if not (isinstance(c, float) and pd.isna(c))]]

    # Transpose: price bands → rows, attributes → columns
    transposed = attr_df.T.copy()
    transposed.index.name = "price_band"
    transposed = transposed.reset_index()

    # Ensure all column names are unique strings
    cols = list(transposed.columns)
    seen_cols = {}
    unique_cols = []
    for c in cols:
        c_str = str(c)
        if c_str in seen_cols:
            seen_cols[c_str] += 1
            unique_cols.append(f"{c_str}_{seen_cols[c_str]}")
        else:
            seen_cols[c_str] = 1
            unique_cols.append(c_str)
    transposed.columns = unique_cols

    # Add node identifier
    transposed.insert(0, "node", node)

    all_transposed.append(transposed)

# Combine all nodes — use outer join so nodes with different numbers of attributes still merge
dsr_transposed = pd.concat(all_transposed, ignore_index=True, join="outer")
print(f"Total rows: {len(dsr_transposed)}")
print(dsr_transposed.shape)

Total rows: 865
(865, 14)

In [8]:
dsr_transposed["Capacity"] = pd.to_numeric(dsr_transposed["Capacity"], errors="coerce")
dsr_transposed = dsr_transposed.dropna(subset=["Capacity"])

# Drop NaN padding columns produced by pd.concat outer join
nan_cols = ["nan", "nan_2", "nan_3", "nan_4", "nan_5", "nan_6"]
dsr_transposed = dsr_transposed.drop(columns=[c for c in nan_cols if c in dsr_transposed.columns])

print(f"Rows after dropping NaN Capacity: {len(dsr_transposed)}")
print(f"Columns: {list(dsr_transposed.columns)}")
print(len(dsr_transposed))
display(dsr_transposed.head(100))

Rows after dropping NaN Capacity: 125
Columns: ['node', 'price_band', 'Capacity', 'Units', 'Hours', 'Price', 'Climate year start', 'Climate year end']
125

,node,price_band,Capacity,Units,Hours,Price,Climate year start,Climate year end
11,AT00,Price Band 1,700.000000,15,24,500,1982,2016
33,BE00,Price Band 1,131.000000,3,1,1000,1982,2016
34,BE00,Price Band 2,53.800000,3,24,1000,1982,2016
35,BE00,Price Band 3,454.000000,3,2,2000,1982,2016
36,BE00,Price Band 4,634.000000,3,4,1500,1982,2016
37,BE00,Price Band 5,540.824028,6,8,500,1982,2016
38,BE00,Price Band 6,193.000000,3,24,300,1982,2016
39,BE00,Price Band 7,202.651658,3,24,178,1982,2016
40,BE00,Price Band 8,620.384935,3,24,67,1982,2016
100,DE00,Price Band 1,288.500000,7,8,5,1982,2016
101,DE00,Price Band 2,1838.700000,14,24,5,1982,2016
102,DE00,Price Band 3,2.700000,7,6,256,1982,2016
103,DE00,Price Band 4,3.200000,7,2,820,1982,2016
104,DE00,Price Band 5,152.400000,7,15,461,1982,2016
105,DE00,Price Band 6,200.100000,7,24,390,1982,2016
106,DE00,Price Band 7,49.400000,7,1,564,1982,2016
107,DE00,Price Band 8,103.600000,7,6,487,1982,2016
108,DE00,Price Band 9,1307.200000,7,24,10,1982,2016
109,DE00,Price Band 10,304.200000,21,24,20,1982,2016
110,DE00,Price Band 11,259.100000,7,24,115,1982,2016
111,DE00,Price Band 12,19.000000,7,24,150,1982,2016
112,DE00,Price Band 13,471.700000,21,24,200,1982,2016
113,DE00,Price Band 14,10000.000000,1,24,87.1,1995,1995
114,DE00,Price Band 14_2,10000.000000,1,24,87.1,2008,2008
115,DE00,Price Band 14_3,10000.000000,1,24,87.1,2009,2009
116,DE00,Price Band 15,8800.000000,1,24,43.6,1995,1995
117,DE00,Price Band 15_2,8800.000000,1,24,43.6,2008,2008
118,DE00,Price Band 15_3,8800.000000,1,24,43.6,2009,2009
198,EE00,Price Band 1,198.000000,1,24,1000,1982,2016
232,ES00,Price Band 1,1000.000000,11,3,700,1982,2016
243,FI00,Price Band 1,287.500000,2,12,50,1982,2016
244,FI00,Price Band 2,862.500000,2,24,75,1982,2016
245,FI00,Price Band 3,650.000000,2,2,100,1982,2016
246,FI00,Price Band 4,940.000000,2,4,150,1982,2016
247,FI00,Price Band 5,950.415788,2,24,160,1982,2016
248,FI00,Price Band 6,950.415788,2,4,240,1982,2016
249,FI00,Price Band 7,0.000000,2,24,250,1982,2016
254,FR00,Price Band 1,1479.800000,14,24,350,1982,2016
255,FR00,Price Band 2,3519.600000,14,10,350,1982,2016
288,GR00,Price Band 1,250.000000,16,6,250,1982,2016
310,HR00,Price Band 1,57.000000,8,24,2999,1982,2016
332,IE00,Price Band 1,504.000000,1,2,3000,1982,2016
333,IE00,Price Band 2,163.000000,12,24,0,1982,2016
366,ITCA,Price Band 1,0.000000,1,24,50,1982,2016
367,ITCA,Price Band 2,0.000000,1,24,75,1982,2016
368,ITCA,Price Band 3,0.000000,1,24,100,1982,2016
369,ITCA,Price Band 4,0.000000,1,24,125,1982,2016
370,ITCA,Price Band 5,0.000000,1,24,150,1982,2016
371,ITCA,Price Band 6,0.000000,1,24,200,1982,2016
372,ITCA,Price Band 7,0.000000,1,24,250,1982,2016
377,ITCN,Price Band 1,0.000000,1,24,50,1982,2016
378,ITCN,Price Band 2,0.000000,1,24,75,1982,2016
379,ITCN,Price Band 3,0.000000,1,24,100,1982,2016
380,ITCN,Price Band 4,0.000000,1,24,125,1982,2016
381,ITCN,Price Band 5,0.000000,1,24,175,1982,2016
382,ITCN,Price Band 6,0.000000,1,24,225,1982,2016
388,ITCS,Price Band 1,0.000000,1,24,50,1982,2016
389,ITCS,Price Band 2,0.000000,1,24,75,1982,2016
390,ITCS,Price Band 3,0.000000,1,24,100,1982,2016
391,ITCS,Price Band 4,0.000000,1,24,125,1982,2016
392,ITCS,Price Band 5,0.000000,1,24,175,1982,2016
393,ITCS,Price Band 6,0.000000,1,24,225,1982,2016
399,ITN1,Price Band 1,0.000000,1,24,50,1982,2016
400,ITN1,Price Band 2,0.000000,1,24,75,1982,2016
401,ITN1,Price Band 3,0.000000,1,24,100,1982,2016
402,ITN1,Price Band 4,0.000000,1,24,125,1982,2016
403,ITN1,Price Band 5,0.000000,1,24,150,1982,2016
404,ITN1,Price Band 6,0.000000,1,24,200,1982,2016
405,ITN1,Price Band 7,0.000000,1,24,225,1982,2016
406,ITN1,Price Band 8,0.000000,1,24,250,1982,2016
410,ITS1,Price Band 1,0.000000,1,24,50,1982,2016
411,ITS1,Price Band 2,0.000000,1,24,75,1982,2016
412,ITS1,Price Band 3,0.000000,1,24,100,1982,2016
413,ITS1,Price Band 4,0.000000,1,24,125,1982,2016
414,ITS1,Price Band 5,0.000000,1,24,150,1982,2016
415,ITS1,Price Band 6,0.000000,1,24,200,1982,2016
416,ITS1,Price Band 7,0.000000,1,24,250,1982,2016
432,ITSI,Price Band 1,0.000000,1,24,50,1982,2016
433,ITSI,Price Band 2,0.000000,1,24,75,1982,2016
434,ITSI,Price Band 3,0.000000,1,24,100,1982,2016
435,ITSI,Price Band 4,0.000000,1,24,125,1982,2016
436,ITSI,Price Band 5,0.000000,1,24,175,1982,2016
437,ITSI,Price Band 6,0.000000,1,24,200,1982,2016
443,LT00,Price Band 1,40.000000,1,4,500,1982,2016
488,LUG1,Price Band 1,45.000000,1,5,500,1982,2016
510,LV00,Price Band 1,10.000000,1,24,150,1982,2016
511,LV00,Price Band 2,20.000000,1,24,200,1982,2016
512,LV00,Price Band 3,40.000000,1,24,300,1982,2016
513,LV00,Price Band 4,80.000000,1,24,500,1982,2016
588,NL00,Price Band 1,1687.000000,4,24,500,1982,2016
655,NOM1,Price Band 1,389.194139,1,8,400,1982,2016
656,NOM1,Price Band 2,107.600733,1,8,700,1982,2016
657,NOM1,Price Band 3,0.000000,1,8,775,1982,2016
658,NOM1,Price Band 4,1058.264652,1,8,950,1982,2016
659,NOM1,Price Band 5,482.486264,1,8,1000,1982,2016
666,NON1,Price Band 1,171.703297,1,8,400,1982,2016
667,NON1,Price Band 2,87.683150,1,8,700,1982,2016
668,NON1,Price Band 3,183.150183,1,8,775,1982,2016
669,NON1,Price Band 4,825.778388,1,8,950,1982,2016
670,NON1,Price Band 5,294.299451,1,8,1000,1982,2016

In [9]:
dsr_transposed.to_csv()

',node,price_band,Capacity,Units,Hours,Price,Climate year start,Climate year end\n11,AT00,Price Band 1,700.0,15,24,500,1982,2016\n33,BE00,Price Band 1,131.0,3,1,1000,1982,2016\n34,BE00,Price Band 2,53.80000000000003,3,24,1000,1982,2016\n35,BE00,Price Band 3,454.0,3,2,2000,1982,2016\n36,BE00,Price Band 4,634.0,3,4,1500,1982,2016\n37,BE00,Price Band 5,540.8240280783971,6,8,500,1982,2016\n38,BE00,Price Band 6,193.0,3,24,300,1982,2016\n39,BE00,Price Band 7,202.6516582352274,3,24,178,1982,2016\n40,BE00,Price Band 8,620.3849346390525,3,24,67,1982,2016\n100,DE00,Price Band 1,288.5,7,8,5,1982,2016\n101,DE00,Price Band 2,1838.7,14,24,5,1982,2016\n102,DE00,Price Band 3,2.7,7,6,256,1982,2016\n103,DE00,Price Band 4,3.2,7,2,820,1982,2016\n104,DE00,Price Band 5,152.4,7,15,461,1982,2016\n105,DE00,Price Band 6,200.1,7,24,390,1982,2016\n106,DE00,Price Band 7,49.39999999999999,7,1,564,1982,2016\n107,DE00,Price Band 8,103.6,7,6,487,1982,2016\n108,DE00,Price Band 9,1307.2,7,24,10,1982,2016\n109,DE00,Price Band 10,304.2,21,24,20,1982,2016\n110,DE00,Price Band 11,259.1,7,24,115,1982,2016\n111,DE00,Price Band 12,19.0,7,24,150,1982,2016\n112,DE00,Price Band 13,471.7,21,24,200,1982,2016\n113,DE00,Price Band 14,10000.0,1,24,87.1,1995,1995\n114,DE00,Price Band 14_2,10000.0,1,24,87.1,2008,2008\n115,DE00,Price Band 14_3,10000.0,1,24,87.1,2009,2009\n116,DE00,Price Band 15,8800.0,1,24,43.6,1995,1995\n117,DE00,Price Band 15_2,8800.0,1,24,43.6,2008,2008\n118,DE00,Price Band 15_3,8800.0,1,24,43.6,2009,2009\n198,EE00,Price Band 1,198.0,1,24,1000,1982,2016\n232,ES00,Price Band 1,1000.0,11,3,700,1982,2016\n243,FI00,Price Band 1,287.5,2,12,50,1982,2016\n244,FI00,Price Band 2,862.5,2,24,75,1982,2016\n245,FI00,Price Band 3,650.0,2,2,100,1982,2016\n246,FI00,Price Band 4,940.0,2,4,150,1982,2016\n247,FI00,Price Band 5,950.4157882011606,2,24,160,1982,2016\n248,FI00,Price Band 6,950.4157882011606,2,4,240,1982,2016\n249,FI00,Price Band 7,0.0,2,24,250,1982,2016\n254,FR00,Price Band 1,1479.8,14,24,350,1982,2016\n255,FR00,Price Band 2,3519.600000000001,14,10,350,1982,2016\n288,GR00,Price Band 1,250.0,16,6,250,1982,2016\n310,HR00,Price Band 1,57.0,8,24,2999,1982,2016\n332,IE00,Price Band 1,504.0,1,2,3000,1982,2016\n333,IE00,Price Band 2,163.0,12,24,0,1982,2016\n366,ITCA,Price Band 1,0.0,1,24,50,1982,2016\n367,ITCA,Price Band 2,0.0,1,24,75,1982,2016\n368,ITCA,Price Band 3,0.0,1,24,100,1982,2016\n369,ITCA,Price Band 4,0.0,1,24,125,1982,2016\n370,ITCA,Price Band 5,0.0,1,24,150,1982,2016\n371,ITCA,Price Band 6,0.0,1,24,200,1982,2016\n372,ITCA,Price Band 7,0.0,1,24,250,1982,2016\n377,ITCN,Price Band 1,0.0,1,24,50,1982,2016\n378,ITCN,Price Band 2,0.0,1,24,75,1982,2016\n379,ITCN,Price Band 3,0.0,1,24,100,1982,2016\n380,ITCN,Price Band 4,0.0,1,24,125,1982,2016\n381,ITCN,Price Band 5,0.0,1,24,175,1982,2016\n382,ITCN,Price Band 6,0.0,1,24,225,1982,2016\n388,ITCS,Price Band 1,0.0,1,24,50,1982,2016\n389,ITCS,Price Band 2,0.0,1,24,75,1982,2016\n390,ITCS,Price Band 3,0.0,1,24,100,1982,2016\n391,ITCS,Price Band 4,0.0,1,24,125,1982,2016\n392,ITCS,Price Band 5,0.0,1,24,175,1982,2016\n393,ITCS,Price Band 6,0.0,1,24,225,1982,2016\n399,ITN1,Price Band 1,0.0,1,24,50,1982,2016\n400,ITN1,Price Band 2,0.0,1,24,75,1982,2016\n401,ITN1,Price Band 3,0.0,1,24,100,1982,2016\n402,ITN1,Price Band 4,0.0,1,24,125,1982,2016\n403,ITN1,Price Band 5,0.0,1,24,150,1982,2016\n404,ITN1,Price Band 6,0.0,1,24,200,1982,2016\n405,ITN1,Price Band 7,0.0,1,24,225,1982,2016\n406,ITN1,Price Band 8,0.0,1,24,250,1982,2016\n410,ITS1,Price Band 1,0.0,1,24,50,1982,2016\n411,ITS1,Price Band 2,0.0,1,24,75,1982,2016\n412,ITS1,Price Band 3,0.0,1,24,100,1982,2016\n413,ITS1,Price Band 4,0.0,1,24,125,1982,2016\n414,ITS1,Price Band 5,0.0,1,24,150,1982,2016\n415,ITS1,Price Band 6,0.0,1,24,200,1982,2016\n416,ITS1,Price Band 7,0.0,1,24,250,1982,2016\n432,ITSI,Price Band 1,0.0,1,24,50,1982,2016\n433,ITSI,Price Band 2,0.0,1,24,75,1982,2016\n434,ITSI,Price Band 3,0.0,1,24,100,1982,2016\n435,ITSI,Price Band 4,0.0,1,24,125,1982,2016\n436,ITSI,Price Band 5,0.0,1,24,175,1982,2016\n437,ITSI,Price Band 6,0.0,1,24,200,1982,2016\n443,LT00,Price Band 1,40.0,1,4,500,1982,2016\n488,LUG1,Price Band 1,45.0,1,5,500,1982,2016\n510,LV00,Price Band 1,10.0,1,24,150,1982,2016\n511,LV00,Price Band 2,20.0,1,24,200,1982,2016\n512,LV00,Price Band 3,40.0,1,24,300,1982,2016\n513,LV00,Price Band 4,80.0,1,24,500,1982,2016\n588,NL00,Price Band 1,1687.0,4,24,500,1982,2016\n655,NOM1,Price Band 1,389.1941391941392,1,8,400,1982,2016\n656,NOM1,Price Band 2,107.6007326007326,1,8,700,1982,2016\n657,NOM1,Price Band 3,0.0,1,8,775,1982,2016\n658,NOM1,Price Band 4,1058.264652014652,1,8,950,1982,2016\n659,NOM1,Price Band 5,482.4862637362637,1,8,1000,1982,2016\n666,NON1,Price Band 1,171.7032967032967,1,8,400,1982,2016\n667,NON1,Price Band 2,87.68315018315019,1,8,700,1982,2016\n668,NON1,Price Band 3,183.1501831501832,1,8,775,1982,2016\n669,NON1,Price Band 4,825.7783882783883,1,8,950,1982,2016\n670,NON1,Price Band 5,294.2994505494505,1,8,1000,1982,2016\n677,NOS0,Price Band 1,172.6190476190476,1,8,400,1982,2016\n678,NOS0,Price Band 2,17.17032967032967,1,8,700,1982,2016\n679,NOS0,Price Band 3,0.0,1,8,775,1982,2016\n680,NOS0,Price Band 4,80.12820512820512,1,8,950,1982,2016\n681,NOS0,Price Band 5,420.1007326007326,1,8,1000,1982,2016\n682,NOS0,Price Band 6,5.723443223443224,1,8,100,1982,2016\n683,NOS0,Price Band 7,58.9514652014652,1,8,400,1982,2016\n684,NOS0,Price Band 8,581.6163003663004,1,8,700,1982,2016\n685,NOS0,Price Band 9,3483.516483516484,2,8,950,1982,2016\n686,NOS0,Price Band 10,1148.466117216117,2,8,1000,1982,2016\n743,SE01,Price Band 1,71.4,1,24,150,1982,2016\n744,SE01,Price Band 2,71.4,1,24,244,1982,2016\n745,SE01,Price Band 3,71.4,1,24,376,1982,2016\n754,SE02,Price Band 1,107.8,1,24,150,1982,2016\n755,SE02,Price Band 2,107.8,1,24,244,1982,2016\n756,SE02,Price Band 3,107.8,1,24,376,1982,2016\n765,SE03,Price Band 1,312.2,1,24,150,1982,2016\n766,SE03,Price Band 2,312.2,1,24,244,1982,2016\n767,SE03,Price Band 3,312.2,1,24,376,1982,2016\n776,SE04,Price Band 1,88.2,1,24,150,1982,2016\n777,SE04,Price Band 2,88.2,1,24,244,1982,2016\n778,SE04,Price Band 3,88.2,1,24,376,1982,2016\n787,SI00,Price Band 1,40.0,1,24,400,1982,2016\n788,SI00,Price Band 2,15.0,3,12,250,1982,2016\n843,UK00,Price Band 1,7438.914696825494,5,8,500,1982,2016\n'

In [10]:

OUTPUT_DIR = Path("../data/open-tyndp")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Drop bands with zero capacity before exporting
dsr_export = dsr_transposed[dsr_transposed["Capacity"] > 0].copy()

dsr_export.to_csv(OUTPUT_DIR / "dsr_pemmdb.csv", index=False)

print("Exported:")
print(f"  → {OUTPUT_DIR / 'dsr_pemmdb.csv'}")
print(f"  Rows: {len(dsr_export)} (dropped {len(dsr_transposed) - len(dsr_export)} zero-capacity bands)")

Exported:
  → ../data/open-tyndp/dsr_pemmdb.csv
  Rows: 82 (dropped 43 zero-capacity bands)

In [11]:
# Filter only price bands valid for climate year 2009
# i.e. Climate year start <= 2009 <= Climate year end
CLIMATE_YEAR = 2009

dsr_2009 = dsr_transposed.copy()
dsr_2009["Climate year start"] = pd.to_numeric(dsr_2009["Climate year start"], errors="coerce")
dsr_2009["Climate year end"]   = pd.to_numeric(dsr_2009["Climate year end"],   errors="coerce")
dsr_2009["Capacity"]           = pd.to_numeric(dsr_2009["Capacity"],           errors="coerce")

dsr_2009 = dsr_2009[
    (dsr_2009["Climate year start"] <= CLIMATE_YEAR) &
    (dsr_2009["Climate year end"]   >= CLIMATE_YEAR)
]

print(f"Rows after filtering for climate year {CLIMATE_YEAR}: {len(dsr_2009)}")

# Total DSR capacity per node [MW]
capacity_by_node_2009 = (
    dsr_2009
    .groupby("node")["Capacity"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
    .rename(columns={"Capacity": "total_capacity_MW"})
)
capacity_by_node_2009

Rows after filtering for climate year 2009: 121

    node  total_capacity_MW
0   DE00       23799.800000
1   UK00        7438.914697
2   NOS0        5968.292125
3   FR00        4999.400000
4   FI00        4640.831576
5   BE00        2829.660621
6   NOM1        2037.545788
7   NL00        1687.000000
8   NON1        1562.614469
9   ES00        1000.000000
10  SE03         936.600000
11  AT00         700.000000
12  IE00         667.000000
13  SE02         323.400000
14  SE04         264.600000
15  GR00         250.000000
16  SE01         214.200000
17  EE00         198.000000
18  LV00         150.000000
19  HR00          57.000000
20  SI00          55.000000
21  LUG1          45.000000
22  LT00          40.000000
23  ITCS           0.000000
24  ITN1           0.000000
25  ITCA           0.000000
26  ITSI           0.000000
27  ITCN           0.000000
28  ITS1           0.000000

In [12]:
print(f"Total DSR capacity (MW): {capacity_by_node_2009['total_capacity_MW'].sum():,.1f} MW")

Total DSR capacity (MW): 59,864.9 MW

In [13]:
print(len(dsr_2009))
dsr_2009

121

,node,price_band,Capacity,Units,Hours,Price,Climate year start,Climate year end
11,AT00,Price Band 1,700.000000,15,24,500,1982,2016
33,BE00,Price Band 1,131.000000,3,1,1000,1982,2016
34,BE00,Price Band 2,53.800000,3,24,1000,1982,2016
35,BE00,Price Band 3,454.000000,3,2,2000,1982,2016
36,BE00,Price Band 4,634.000000,3,4,1500,1982,2016
37,BE00,Price Band 5,540.824028,6,8,500,1982,2016
38,BE00,Price Band 6,193.000000,3,24,300,1982,2016
39,BE00,Price Band 7,202.651658,3,24,178,1982,2016
40,BE00,Price Band 8,620.384935,3,24,67,1982,2016
100,DE00,Price Band 1,288.500000,7,8,5,1982,2016
101,DE00,Price Band 2,1838.700000,14,24,5,1982,2016
102,DE00,Price Band 3,2.700000,7,6,256,1982,2016
103,DE00,Price Band 4,3.200000,7,2,820,1982,2016
104,DE00,Price Band 5,152.400000,7,15,461,1982,2016
105,DE00,Price Band 6,200.100000,7,24,390,1982,2016
106,DE00,Price Band 7,49.400000,7,1,564,1982,2016
107,DE00,Price Band 8,103.600000,7,6,487,1982,2016
108,DE00,Price Band 9,1307.200000,7,24,10,1982,2016
109,DE00,Price Band 10,304.200000,21,24,20,1982,2016
110,DE00,Price Band 11,259.100000,7,24,115,1982,2016
111,DE00,Price Band 12,19.000000,7,24,150,1982,2016
112,DE00,Price Band 13,471.700000,21,24,200,1982,2016
115,DE00,Price Band 14_3,10000.000000,1,24,87.1,2009,2009
118,DE00,Price Band 15_3,8800.000000,1,24,43.6,2009,2009
198,EE00,Price Band 1,198.000000,1,24,1000,1982,2016
232,ES00,Price Band 1,1000.000000,11,3,700,1982,2016
243,FI00,Price Band 1,287.500000,2,12,50,1982,2016
244,FI00,Price Band 2,862.500000,2,24,75,1982,2016
245,FI00,Price Band 3,650.000000,2,2,100,1982,2016
246,FI00,Price Band 4,940.000000,2,4,150,1982,2016
247,FI00,Price Band 5,950.415788,2,24,160,1982,2016
248,FI00,Price Band 6,950.415788,2,4,240,1982,2016
249,FI00,Price Band 7,0.000000,2,24,250,1982,2016
254,FR00,Price Band 1,1479.800000,14,24,350,1982,2016
255,FR00,Price Band 2,3519.600000,14,10,350,1982,2016
288,GR00,Price Band 1,250.000000,16,6,250,1982,2016
310,HR00,Price Band 1,57.000000,8,24,2999,1982,2016
332,IE00,Price Band 1,504.000000,1,2,3000,1982,2016
333,IE00,Price Band 2,163.000000,12,24,0,1982,2016
366,ITCA,Price Band 1,0.000000,1,24,50,1982,2016
367,ITCA,Price Band 2,0.000000,1,24,75,1982,2016
368,ITCA,Price Band 3,0.000000,1,24,100,1982,2016
369,ITCA,Price Band 4,0.000000,1,24,125,1982,2016
370,ITCA,Price Band 5,0.000000,1,24,150,1982,2016
371,ITCA,Price Band 6,0.000000,1,24,200,1982,2016
372,ITCA,Price Band 7,0.000000,1,24,250,1982,2016
377,ITCN,Price Band 1,0.000000,1,24,50,1982,2016
378,ITCN,Price Band 2,0.000000,1,24,75,1982,2016
379,ITCN,Price Band 3,0.000000,1,24,100,1982,2016
380,ITCN,Price Band 4,0.000000,1,24,125,1982,2016
381,ITCN,Price Band 5,0.000000,1,24,175,1982,2016
382,ITCN,Price Band 6,0.000000,1,24,225,1982,2016
388,ITCS,Price Band 1,0.000000,1,24,50,1982,2016
389,ITCS,Price Band 2,0.000000,1,24,75,1982,2016
390,ITCS,Price Band 3,0.000000,1,24,100,1982,2016
391,ITCS,Price Band 4,0.000000,1,24,125,1982,2016
392,ITCS,Price Band 5,0.000000,1,24,175,1982,2016
393,ITCS,Price Band 6,0.000000,1,24,225,1982,2016
399,ITN1,Price Band 1,0.000000,1,24,50,1982,2016
400,ITN1,Price Band 2,0.000000,1,24,75,1982,2016
401,ITN1,Price Band 3,0.000000,1,24,100,1982,2016
402,ITN1,Price Band 4,0.000000,1,24,125,1982,2016
403,ITN1,Price Band 5,0.000000,1,24,150,1982,2016
404,ITN1,Price Band 6,0.000000,1,24,200,1982,2016
405,ITN1,Price Band 7,0.000000,1,24,225,1982,2016
406,ITN1,Price Band 8,0.000000,1,24,250,1982,2016
410,ITS1,Price Band 1,0.000000,1,24,50,1982,2016
411,ITS1,Price Band 2,0.000000,1,24,75,1982,2016
412,ITS1,Price Band 3,0.000000,1,24,100,1982,2016
413,ITS1,Price Band 4,0.000000,1,24,125,1982,2016
414,ITS1,Price Band 5,0.000000,1,24,150,1982,2016
415,ITS1,Price Band 6,0.000000,1,24,200,1982,2016
416,ITS1,Price Band 7,0.000000,1,24,250,1982,2016
432,ITSI,Price Band 1,0.000000,1,24,50,1982,2016
433,ITSI,Price Band 2,0.000000,1,24,75,1982,2016
434,ITSI,Price Band 3,0.000000,1,24,100,1982,2016
435,ITSI,Price Band 4,0.000000,1,24,125,1982,2016
436,ITSI,Price Band 5,0.000000,1,24,175,1982,2016
437,ITSI,Price Band 6,0.000000,1,24,200,1982,2016
443,LT00,Price Band 1,40.000000,1,4,500,1982,2016
488,LUG1,Price Band 1,45.000000,1,5,500,1982,2016
510,LV00,Price Band 1,10.000000,1,24,150,1982,2016
511,LV00,Price Band 2,20.000000,1,24,200,1982,2016
512,LV00,Price Band 3,40.000000,1,24,300,1982,2016
513,LV00,Price Band 4,80.000000,1,24,500,1982,2016
588,NL00,Price Band 1,1687.000000,4,24,500,1982,2016
655,NOM1,Price Band 1,389.194139,1,8,400,1982,2016
656,NOM1,Price Band 2,107.600733,1,8,700,1982,2016
657,NOM1,Price Band 3,0.000000,1,8,775,1982,2016
658,NOM1,Price Band 4,1058.264652,1,8,950,1982,2016
659,NOM1,Price Band 5,482.486264,1,8,1000,1982,2016
666,NON1,Price Band 1,171.703297,1,8,400,1982,2016
667,NON1,Price Band 2,87.683150,1,8,700,1982,2016
668,NON1,Price Band 3,183.150183,1,8,775,1982,2016
669,NON1,Price Band 4,825.778388,1,8,950,1982,2016
670,NON1,Price Band 5,294.299451,1,8,1000,1982,2016
677,NOS0,Price Band 1,172.619048,1,8,400,1982,2016
678,NOS0,Price Band 2,17.170330,1,8,700,1982,2016
679,NOS0,Price Band 3,0.000000,1,8,775,1982,2016
680,NOS0,Price Band 4,80.128205,1,8,950,1982,2016
681,NOS0,Price Band 5,420.100733,1,8,1000,1982,2016
682,NOS0,Price Band 6,5.723443,1,8,100,1982,2016
683,NOS0,Price Band 7,58.951465,1,8,400,1982,2016
684,NOS0,Price Band 8,581.616300,1,8,700,1982,2016
685,NOS0,Price Band 9,3483.516484,2,8,950,1982,2016
686,NOS0,Price Band 10,1148.466117,2,8,1000,1982,2016
743,SE01,Price Band 1,71.400000,1,24,150,1982,2016
744,SE01,Price Band 2,71.400000,1,24,244,1982,2016
745,SE01,Price Band 3,71.400000,1,24,376,1982,2016
754,SE02,Price Band 1,107.800000,1,24,150,1982,2016
755,SE02,Price Band 2,107.800000,1,24,244,1982,2016
756,SE02,Price Band 3,107.800000,1,24,376,1982,2016
765,SE03,Price Band 1,312.200000,1,24,150,1982,2016
766,SE03,Price Band 2,312.200000,1,24,244,1982,2016
767,SE03,Price Band 3,312.200000,1,24,376,1982,2016
776,SE04,Price Band 1,88.200000,1,24,150,1982,2016
777,SE04,Price Band 2,88.200000,1,24,244,1982,2016
778,SE04,Price Band 3,88.200000,1,24,376,1982,2016
787,SI00,Price Band 1,40.000000,1,24,400,1982,2016
788,SI00,Price Band 2,15.000000,3,12,250,1982,2016
843,UK00,Price Band 1,7438.914697,5,8,500,1982,2016

In [14]:
dsr_2009

,node,price_band,Capacity,Units,Hours,Price,Climate year start,Climate year end
11,AT00,Price Band 1,700.000000,15,24,500,1982,2016
33,BE00,Price Band 1,131.000000,3,1,1000,1982,2016
34,BE00,Price Band 2,53.800000,3,24,1000,1982,2016
35,BE00,Price Band 3,454.000000,3,2,2000,1982,2016
36,BE00,Price Band 4,634.000000,3,4,1500,1982,2016
37,BE00,Price Band 5,540.824028,6,8,500,1982,2016
38,BE00,Price Band 6,193.000000,3,24,300,1982,2016
39,BE00,Price Band 7,202.651658,3,24,178,1982,2016
40,BE00,Price Band 8,620.384935,3,24,67,1982,2016
100,DE00,Price Band 1,288.500000,7,8,5,1982,2016
101,DE00,Price Band 2,1838.700000,14,24,5,1982,2016
102,DE00,Price Band 3,2.700000,7,6,256,1982,2016
103,DE00,Price Band 4,3.200000,7,2,820,1982,2016
104,DE00,Price Band 5,152.400000,7,15,461,1982,2016
105,DE00,Price Band 6,200.100000,7,24,390,1982,2016
106,DE00,Price Band 7,49.400000,7,1,564,1982,2016
107,DE00,Price Band 8,103.600000,7,6,487,1982,2016
108,DE00,Price Band 9,1307.200000,7,24,10,1982,2016
109,DE00,Price Band 10,304.200000,21,24,20,1982,2016
110,DE00,Price Band 11,259.100000,7,24,115,1982,2016
111,DE00,Price Band 12,19.000000,7,24,150,1982,2016
112,DE00,Price Band 13,471.700000,21,24,200,1982,2016
115,DE00,Price Band 14_3,10000.000000,1,24,87.1,2009,2009
118,DE00,Price Band 15_3,8800.000000,1,24,43.6,2009,2009
198,EE00,Price Band 1,198.000000,1,24,1000,1982,2016
232,ES00,Price Band 1,1000.000000,11,3,700,1982,2016
243,FI00,Price Band 1,287.500000,2,12,50,1982,2016
244,FI00,Price Band 2,862.500000,2,24,75,1982,2016
245,FI00,Price Band 3,650.000000,2,2,100,1982,2016
246,FI00,Price Band 4,940.000000,2,4,150,1982,2016
247,FI00,Price Band 5,950.415788,2,24,160,1982,2016
248,FI00,Price Band 6,950.415788,2,4,240,1982,2016
249,FI00,Price Band 7,0.000000,2,24,250,1982,2016
254,FR00,Price Band 1,1479.800000,14,24,350,1982,2016
255,FR00,Price Band 2,3519.600000,14,10,350,1982,2016
288,GR00,Price Band 1,250.000000,16,6,250,1982,2016
310,HR00,Price Band 1,57.000000,8,24,2999,1982,2016
332,IE00,Price Band 1,504.000000,1,2,3000,1982,2016
333,IE00,Price Band 2,163.000000,12,24,0,1982,2016
366,ITCA,Price Band 1,0.000000,1,24,50,1982,2016
367,ITCA,Price Band 2,0.000000,1,24,75,1982,2016
368,ITCA,Price Band 3,0.000000,1,24,100,1982,2016
369,ITCA,Price Band 4,0.000000,1,24,125,1982,2016
370,ITCA,Price Band 5,0.000000,1,24,150,1982,2016
371,ITCA,Price Band 6,0.000000,1,24,200,1982,2016
372,ITCA,Price Band 7,0.000000,1,24,250,1982,2016
377,ITCN,Price Band 1,0.000000,1,24,50,1982,2016
378,ITCN,Price Band 2,0.000000,1,24,75,1982,2016
379,ITCN,Price Band 3,0.000000,1,24,100,1982,2016
380,ITCN,Price Band 4,0.000000,1,24,125,1982,2016
381,ITCN,Price Band 5,0.000000,1,24,175,1982,2016
382,ITCN,Price Band 6,0.000000,1,24,225,1982,2016
388,ITCS,Price Band 1,0.000000,1,24,50,1982,2016
389,ITCS,Price Band 2,0.000000,1,24,75,1982,2016
390,ITCS,Price Band 3,0.000000,1,24,100,1982,2016
391,ITCS,Price Band 4,0.000000,1,24,125,1982,2016
392,ITCS,Price Band 5,0.000000,1,24,175,1982,2016
393,ITCS,Price Band 6,0.000000,1,24,225,1982,2016
399,ITN1,Price Band 1,0.000000,1,24,50,1982,2016
400,ITN1,Price Band 2,0.000000,1,24,75,1982,2016
401,ITN1,Price Band 3,0.000000,1,24,100,1982,2016
402,ITN1,Price Band 4,0.000000,1,24,125,1982,2016
403,ITN1,Price Band 5,0.000000,1,24,150,1982,2016
404,ITN1,Price Band 6,0.000000,1,24,200,1982,2016
405,ITN1,Price Band 7,0.000000,1,24,225,1982,2016
406,ITN1,Price Band 8,0.000000,1,24,250,1982,2016
410,ITS1,Price Band 1,0.000000,1,24,50,1982,2016
411,ITS1,Price Band 2,0.000000,1,24,75,1982,2016
412,ITS1,Price Band 3,0.000000,1,24,100,1982,2016
413,ITS1,Price Band 4,0.000000,1,24,125,1982,2016
414,ITS1,Price Band 5,0.000000,1,24,150,1982,2016
415,ITS1,Price Band 6,0.000000,1,24,200,1982,2016
416,ITS1,Price Band 7,0.000000,1,24,250,1982,2016
432,ITSI,Price Band 1,0.000000,1,24,50,1982,2016
433,ITSI,Price Band 2,0.000000,1,24,75,1982,2016
434,ITSI,Price Band 3,0.000000,1,24,100,1982,2016
435,ITSI,Price Band 4,0.000000,1,24,125,1982,2016
436,ITSI,Price Band 5,0.000000,1,24,175,1982,2016
437,ITSI,Price Band 6,0.000000,1,24,200,1982,2016
443,LT00,Price Band 1,40.000000,1,4,500,1982,2016
488,LUG1,Price Band 1,45.000000,1,5,500,1982,2016
510,LV00,Price Band 1,10.000000,1,24,150,1982,2016
511,LV00,Price Band 2,20.000000,1,24,200,1982,2016
512,LV00,Price Band 3,40.000000,1,24,300,1982,2016
513,LV00,Price Band 4,80.000000,1,24,500,1982,2016
588,NL00,Price Band 1,1687.000000,4,24,500,1982,2016
655,NOM1,Price Band 1,389.194139,1,8,400,1982,2016
656,NOM1,Price Band 2,107.600733,1,8,700,1982,2016
657,NOM1,Price Band 3,0.000000,1,8,775,1982,2016
658,NOM1,Price Band 4,1058.264652,1,8,950,1982,2016
659,NOM1,Price Band 5,482.486264,1,8,1000,1982,2016
666,NON1,Price Band 1,171.703297,1,8,400,1982,2016
667,NON1,Price Band 2,87.683150,1,8,700,1982,2016
668,NON1,Price Band 3,183.150183,1,8,775,1982,2016
669,NON1,Price Band 4,825.778388,1,8,950,1982,2016
670,NON1,Price Band 5,294.299451,1,8,1000,1982,2016
677,NOS0,Price Band 1,172.619048,1,8,400,1982,2016
678,NOS0,Price Band 2,17.170330,1,8,700,1982,2016
679,NOS0,Price Band 3,0.000000,1,8,775,1982,2016
680,NOS0,Price Band 4,80.128205,1,8,950,1982,2016
681,NOS0,Price Band 5,420.100733,1,8,1000,1982,2016
682,NOS0,Price Band 6,5.723443,1,8,100,1982,2016
683,NOS0,Price Band 7,58.951465,1,8,400,1982,2016
684,NOS0,Price Band 8,581.616300,1,8,700,1982,2016
685,NOS0,Price Band 9,3483.516484,2,8,950,1982,2016
686,NOS0,Price Band 10,1148.466117,2,8,1000,1982,2016
743,SE01,Price Band 1,71.400000,1,24,150,1982,2016
744,SE01,Price Band 2,71.400000,1,24,244,1982,2016
745,SE01,Price Band 3,71.400000,1,24,376,1982,2016
754,SE02,Price Band 1,107.800000,1,24,150,1982,2016
755,SE02,Price Band 2,107.800000,1,24,244,1982,2016
756,SE02,Price Band 3,107.800000,1,24,376,1982,2016
765,SE03,Price Band 1,312.200000,1,24,150,1982,2016
766,SE03,Price Band 2,312.200000,1,24,244,1982,2016
767,SE03,Price Band 3,312.200000,1,24,376,1982,2016
776,SE04,Price Band 1,88.200000,1,24,150,1982,2016
777,SE04,Price Band 2,88.200000,1,24,244,1982,2016
778,SE04,Price Band 3,88.200000,1,24,376,1982,2016
787,SI00,Price Band 1,40.000000,1,24,400,1982,2016
788,SI00,Price Band 2,15.000000,3,12,250,1982,2016
843,UK00,Price Band 1,7438.914697,5,8,500,1982,2016

In [15]:
# Load DSR capacities from TYNDP2024 Flexibility CSV for climate year 2009
FLEXIBILITY_CSV = Path("../data/tyndp2024/250117_TYNDP2024Scenarios_Electricity_Flexibility.csv")

flex_df = pd.read_csv(FLEXIBILITY_CSV, sep=";", decimal=",")

# Filter: DSR Explicit category, year 2030, National Trends scenario, CY2009, unit GW
dsr_tyndp = flex_df[
    (flex_df["Category_Simple"] == "DSR Explicit") &
    (flex_df["Year"] == 2030) &
    (flex_df["Scenario"] == "National Trends") &
    (flex_df["Climate_Year"] == "CY2009") &
    (flex_df["Unit_Name"] == "GW")
][["Country", "Value", "Unit_Name"]].copy()

dsr_tyndp = dsr_tyndp.rename(columns={"Country": "country", "Value": "dsr_GW", "Unit_Name": "unit"})
dsr_tyndp = dsr_tyndp.sort_values("dsr_GW", ascending=False).reset_index(drop=True)

print(f"DSR entries for CY2009 [GW]: {len(dsr_tyndp)}")
dsr_tyndp

DSR entries for CY2009 [GW]: 18

        country     dsr_GW unit
0       Germany  23.799800   GW
1        Norway   9.568449   GW
2            UK   7.438915   GW
3        France   5.000900   GW
4       Finland   4.640832   GW
5       Belgium   2.829661   GW
6        Sweden   1.738800   GW
7   Netherlands   1.687000   GW
8         Spain   1.000000   GW
9       Austria   0.700000   GW
10      Ireland   0.667000   GW
11       Greece   0.250000   GW
12      Estonia   0.198000   GW
13       Latvia   0.150000   GW
14      Croatia   0.057000   GW
15     Slovenia   0.055000   GW
16   Luxembourg   0.045000   GW
17    Lithuania   0.040000   GW

In [16]:
dsr_tyndp

        country     dsr_GW unit
0       Germany  23.799800   GW
1        Norway   9.568449   GW
2            UK   7.438915   GW
3        France   5.000900   GW
4       Finland   4.640832   GW
5       Belgium   2.829661   GW
6        Sweden   1.738800   GW
7   Netherlands   1.687000   GW
8         Spain   1.000000   GW
9       Austria   0.700000   GW
10      Ireland   0.667000   GW
11       Greece   0.250000   GW
12      Estonia   0.198000   GW
13       Latvia   0.150000   GW
14      Croatia   0.057000   GW
15     Slovenia   0.055000   GW
16   Luxembourg   0.045000   GW
17    Lithuania   0.040000   GW

In [17]:
print(f"Total DSR capacity (GW): {dsr_tyndp['dsr_GW'].sum():.2f} GW")

Total DSR capacity (GW): 59.87 GW

## Parse Timeseries
- p_max_pu

In [18]:

import pandas as pd
from pathlib import Path

PEMMDB_DIR = Path("../data/tyndp2024/PEMMDB2/2030")
DSR_SHEET = "DSR"
OUTPUT_DIR = Path("../data/open-tyndp")
CLIMATE_YEAR_TS = 2009

# Build a year-2030 date range (8760 hours, hour 1 = 00:00)
timestamps = pd.date_range("2030-01-01 00:00", periods=8760, freq="h")

all_cols = {}

for xlsx_file in sorted(PEMMDB_DIR.glob("*.xlsx")):
    node = xlsx_file.stem.split("_")[1]

    try:
        raw = pd.read_excel(xlsx_file, sheet_name=DSR_SHEET, header=None)
    except Exception as e:
        print(f"✗ {xlsx_file.name}: {e}")
        continue

    # ── 1. Read static metadata (rows 7-13) ──────────────────────────────────
    band_names_raw = raw.iloc[7,  2:].tolist()
    capacities_raw = raw.iloc[8,  2:].tolist()
    cy_start_raw   = raw.iloc[12, 2:].tolist()
    cy_end_raw     = raw.iloc[13, 2:].tolist()

    # ── 2. Deduplicate band names globally (matching dsr_pemmdb.csv logic) ───
    seen = {}
    deduped_names = []
    for name in band_names_raw:
        if pd.isna(name):
            deduped_names.append(None)
            continue
        name_str = str(name).strip()
        if name_str in seen:
            seen[name_str] += 1
            deduped_names.append(f"{name_str}_{seen[name_str]}")
        else:
            seen[name_str] = 1
            deduped_names.append(name_str)

    # ── 3. Filter: capacity > 0 AND climate year start <= 2009 <= climate year end ──
    labeled = []
    for i, (band, cap, cy_s, cy_e) in enumerate(zip(deduped_names, capacities_raw, cy_start_raw, cy_end_raw)):
        if band is None:
            continue
        try:
            cap  = float(cap)
            cy_s = int(float(cy_s))
            cy_e = int(float(cy_e))
        except (ValueError, TypeError):
            continue
        if pd.isna(cap) or cap <= 0:
            continue
        if not (cy_s <= CLIMATE_YEAR_TS <= cy_e):
            continue
        labeled.append((i, band, cap))

    if not labeled:
        print(f"  {node}: no bands for CY{CLIMATE_YEAR_TS}, skipping")
        continue

    # ── 4. Extract timeseries rows (row 15 onwards = index 15, 8760 rows) ────
    ts_data = raw.iloc[15:15 + 8760].reset_index(drop=True)

    for raw_col_idx, band, capacity in labeled:
        col_key = f"{node}_{band}"
        ts_col = ts_data.iloc[:, raw_col_idx + 2]   # +2 for Date and Hour offset
        ts_values = pd.to_numeric(ts_col, errors="coerce").fillna(0.0)
        # p_max_pu = available_MW / capacity_MW  (clipped to [0, 1])
        p_max_pu = (ts_values / capacity).clip(0.0, 1.0)
        all_cols[col_key] = p_max_pu.values

    print(f"✓ {node}: {len(labeled)} bands")

# ── 5. Build final DataFrame ─────────────────────────────────────────────────
dsr_timeseries = pd.DataFrame(all_cols, index=timestamps)
dsr_timeseries.index.name = "timestamp"

print(f"\nTimeseries shape: {dsr_timeseries.shape}")
de_cols = [c for c in dsr_timeseries.columns if c.startswith("DE00_")]
print(f"DE00 bands ({len(de_cols)}): {[c.replace('DE00_', '') for c in de_cols]}")
dsr_timeseries.head()

  AL00: no bands for CY2009, skipping
✓ AT00: 1 bands
  BA00: no bands for CY2009, skipping
✓ BE00: 8 bands
  BEOF: no bands for CY2009, skipping
  BG00: no bands for CY2009, skipping
  CH00: no bands for CY2009, skipping
  CY00: no bands for CY2009, skipping
  CZ00: no bands for CY2009, skipping
✓ DE00: 15 bands
  DEKF: no bands for CY2009, skipping
  DKBH: no bands for CY2009, skipping
  DKE1: no bands for CY2009, skipping
  DKKF: no bands for CY2009, skipping
  DKNS: no bands for CY2009, skipping
  DKW1: no bands for CY2009, skipping
  DZ00: no bands for CY2009, skipping
✓ EE00: 1 bands
  EEOF: no bands for CY2009, skipping
  EG00: no bands for CY2009, skipping
✓ ES00: 1 bands
✓ FI00: 6 bands
✓ FR00: 2 bands
✓ FR15: 1 bands
  GE00: no bands for CY2009, skipping
✓ GR00: 1 bands
  GR03: no bands for CY2009, skipping
✓ HR00: 1 bands
  HU00: no bands for CY2009, skipping
✓ IE00: 2 bands
  IL00: no bands for CY2009, skipping
  ITA00: no bands for CY2009, skipping
  ITCA: no bands for CY2009, skipping
  ITCN: no bands for CY2009, skipping
  ITCS: no bands for CY2009, skipping
  ITN1: no bands for CY2009, skipping
  ITS1: no bands for CY2009, skipping
  ITSA: no bands for CY2009, skipping
  ITSI: no bands for CY2009, skipping
✓ LT00: 1 bands
  LTOF: no bands for CY2009, skipping
  LUB1: no bands for CY2009, skipping
  LUF1: no bands for CY2009, skipping
✓ LUG1: 1 bands
  LUV1: no bands for CY2009, skipping
✓ LV00: 4 bands
  LY00: no bands for CY2009, skipping
  MA00: no bands for CY2009, skipping
  MD00: no bands for CY2009, skipping
  ME00: no bands for CY2009, skipping
  MK00: no bands for CY2009, skipping
  MT00: no bands for CY2009, skipping
✓ NL00: 1 bands
  NL60: no bands for CY2009, skipping
  NL6H: no bands for CY2009, skipping
  NLA0: no bands for CY2009, skipping
  NLBH: no bands for CY2009, skipping
  NLLL: no bands for CY2009, skipping
✓ NOM1: 4 bands
✓ NON1: 5 bands
✓ NOS0: 9 bands
  PL00: no bands for CY2009, skipping
  PS00: no bands for CY2009, skipping
  PT00: no bands for CY2009, skipping
  RO00: no bands for CY2009, skipping
  RS00: no bands for CY2009, skipping
✓ SE01: 3 bands
✓ SE02: 3 bands
✓ SE03: 3 bands
✓ SE04: 3 bands
✓ SI00: 2 bands
  SK00: no bands for CY2009, skipping
  TN00: no bands for CY2009, skipping
  TR00: no bands for CY2009, skipping
  UA00: no bands for CY2009, skipping
✓ UK00: 1 bands
  UKNI: no bands for CY2009, skipping
✗ ~$PEMMDB_DE00_NationalTrends_2030.xlsx: Excel file format cannot be determined, you must specify an engine manually.
✗ ~$PEMMDB_ITSA_NationalTrends_2030.xlsx: Excel file format cannot be determined, you must specify an engine manually.

Timeseries shape: (8760, 79)
DE00 bands (15): ['Price Band 1', 'Price Band 2', 'Price Band 3', 'Price Band 4', 'Price Band 5', 'Price Band 6', 'Price Band 7', 'Price Band 8', 'Price Band 9', 'Price Band 10', 'Price Band 11', 'Price Band 12', 'Price Band 13', 'Price Band 14_3', 'Price Band 15_3']

,AT00_Price Band 1,BE00_Price Band 1,BE00_Price Band 2,BE00_Price Band 3,BE00_Price Band 4,BE00_Price Band 5,BE00_Price Band 6,BE00_Price Band 7,BE00_Price Band 8,DE00_Price Band 1,DE00_Price Band 2,DE00_Price Band 3,DE00_Price Band 4,DE00_Price Band 5,DE00_Price Band 6,DE00_Price Band 7,DE00_Price Band 8,DE00_Price Band 9,DE00_Price Band 10,DE00_Price Band 11,DE00_Price Band 12,DE00_Price Band 13,DE00_Price Band 14_3,DE00_Price Band 15_3,EE00_Price Band 1,ES00_Price Band 1,FI00_Price Band 1,FI00_Price Band 2,FI00_Price Band 3,FI00_Price Band 4,FI00_Price Band 5,FI00_Price Band 6,FR00_Price Band 1,FR00_Price Band 2,FR15_Price Band 1,GR00_Price Band 1,HR00_Price Band 1,IE00_Price Band 1,IE00_Price Band 2,LT00_Price Band 1,LUG1_Price Band 1,LV00_Price Band 1,LV00_Price Band 2,LV00_Price Band 3,LV00_Price Band 4,NL00_Price Band 1,NOM1_Price Band 1,NOM1_Price Band 2,NOM1_Price Band 4,NOM1_Price Band 5,NON1_Price Band 1,NON1_Price Band 2,NON1_Price Band 3,NON1_Price Band 4,NON1_Price Band 5,NOS0_Price Band 1,NOS0_Price Band 2,NOS0_Price Band 4,NOS0_Price Band 5,NOS0_Price Band 6,NOS0_Price Band 7,NOS0_Price Band 8,NOS0_Price Band 9,NOS0_Price Band 10,SE01_Price Band 1,SE01_Price Band 2,SE01_Price Band 3,SE02_Price Band 1,SE02_Price Band 2,SE02_Price Band 3,SE03_Price Band 1,SE03_Price Band 2,SE03_Price Band 3,SE04_Price Band 1,SE04_Price Band 2,SE04_Price Band 3,SI00_Price Band 1,SI00_Price Band 2,UK00_Price Band 1
timestamp,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2030-01-01 00:00:00,0.0,1.0,1.0,1.0,0.14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.414,0.414,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.794911,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.8688
2030-01-01 01:00:00,0.0,1.0,1.0,1.0,0.14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.415,0.415,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.656602,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.8688
2030-01-01 02:00:00,0.0,1.0,1.0,1.0,0.14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.433,0.433,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.223889,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.8688
2030-01-01 03:00:00,0.0,1.0,1.0,1.0,0.14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.478,0.478,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.214044,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.8688
2030-01-01 04:00:00,0.0,1.0,1.0,1.0,0.14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.581,0.581,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.642762,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.8688

In [19]:

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
out_path = OUTPUT_DIR / "dsr_p_max_pu_timeseries.csv"
dsr_timeseries.to_csv(out_path)
print(f"Exported → {out_path}")
print(f"Shape: {dsr_timeseries.shape}")

Exported → ../data/open-tyndp/dsr_p_max_pu_timeseries.csv
Shape: (8760, 79)